version: '2'
services:
    jpa-mysql:
        image: mysql:5.7.26
        restart: always
        container_name: jpa-mysql
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        volumes:
            - ./mysql:/var/lib/mysql
        ports:
            - 3306:3306
    jpa-phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        container_name: jpa-phpmyadmin
        ports:
            - "8085:80"
        environment:
            - PMA_HOST=jpa-mysql
        links:
            - jpa-mysql
        depends_on:
          - jpa-mysql
